### ISSUE TITLE
[Health Check Service] Implement a Health Check Service for OVE

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-services#27]
Scope should include:
- Back-ends/servers
- Browser nodes
- Applications
- Key µServices and APIs

**Comment by davidbirchwork** [comment]
Happy to help with this

**Comment by senakafdo** [comment]
The following endpoints can be used to check if OVE components are up and running.
1. Core: http://OVE_HOST/sections?geometry=0,0,0,0
2. Apps: http://OVE_APP_HOST/name
3. Persistence Services: http://OVE_PERSISTENCE_SERVICE_HOST/empty
