### ISSUE TITLE
Examples on using TileService APIs

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-services#4]
Provide examples on how to use the TileService APIs as a part of the TileService Swagger specification, similar to [other APIs](http://localhost:8081/api-docs).

**Comment by davidbirchwork** [comment]
Nothing complex here, this works
![image](https://user-images.githubusercontent.com/11289564/46741811-af6eb500-cc9d-11e8-83e0-d848481c03c9.png)

will improve documentation in next PR

**Comment by senakafdo** [comment]
I will see if the same can be done on curl. And, yes, look forward to the docs improvements.

**Comment by davidbirchwork** [comment]
curl -X POST \
  http://localhost:5000/OVEAssetModelController/Create \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -H 'postman-token: ebf36bd1-d4e3-0fe7-55e4-d916bd10eef8' \
  -F upload=@night.PNG \
  -F Project=davidtest \
  -F Name=something \
  -F Service=Images

**Comment by senakafdo** [comment]
@davidbirchwork, not sure if this was closed by mistake. The objective here was to document the way in which the APIs are used, _in Swagger_. Can we reopen, unless you do not intend to fix this?
