### ISSUE TITLE
Improving usability of Asset Manager User interface

### ISSUE THREAD

**Issue by senakafdo** [ove/ove-services#5]
It is not straightforward to an end user right now as to where did the image land.

**Comment by davidbirchwork** [comment]
Currently this is available via API as requested. 
I can seek to make this viewable through HTML also

**Comment by senakafdo** [comment]
@davidbirchwork, yes please - that will improve the usability of the UI, since the person uploading an image cannot confirm on their own that the DZI is existing apart from the processing state being set to 4.

**Comment by jamesscottbrown** [comment]
Also, could the processing state be displayed as a word/description, rather than as a number?

(I don't have the latest version of the service built on my machine, so apologies if it already does this.)

**Comment by senakafdo** [comment]
@jamesscottbrown, that's a good suggestion - it does not do it right now. Also, you can easily build the service now (using Docker) - you will however need credentials (these are private) to connect to an object store.

**Comment by davidbirchwork** [comment]
The processing state is stored in words in a separate string field called something like Processing Errors. This field is currently not visible in the edit page as users should not edit it. I'll make it visible but read only. 

The reason for two fields (I'm sure your about to ask) is that we need a concurrent atomic update of the state across all instances of the microservices consuming these files. This is easier with an integer field. It is possible with a string field but it makes it more complex to log error details and I;d rather keep things simple ;-)

**Comment by senakafdo** [comment]
@davidbirchwork, I believe that the suggestion here is to keep storing it as an integer but to display it on the details page as a string (ideally via an enumeration that maps integers to strings). The objective would not be to display processing errors as a replacement as far as I understand.

**Comment by davidbirchwork** [comment]
Rational for displaying both is that:
 -  users may wish to reset processing state to zero to re-try processing
 - displaying error messages is necessary for users to fix errors for example cause may be illformated image or memory exception 

yes an enum is an option i will explore.

**Comment by miguems** [comment]
This will be helpful:
https://www.sohamkamani.com/blog/2017/08/21/enums-in-javascript/

Best!

**Comment by DavidAkroyd** [comment]
Changing issue to recognise the change from purely an image loader to an asset manager

**Comment by DavidAkroyd** [comment]
In regards to the processing state, users should never need to specify an unknown variable in order to reset a processing. If this is required, at the very least, there should be a "Reset processing" button that changes the processing behind the scene.
For this to be suitable for a third party user, it should be highly intuitive and suitable for someone without a computing background knowledge. As a result, unnecessary fields should be removed, or represented in a user suitable/understandable format.

For the DZI however, I do not believe that there is a requirement to provide an html link - an uploader has no requirement outside of using an API from another program to use the object store link directly, especially when a security model is brought in that will block access to the unauthenticated user

**Comment by senakafdo** [comment]
@DavidAkroyd, re:url agree. I think we need not provide the StorageLocation altogether. Right now, it means nothing hence the request to change to the DZI URL. However, the API should probably return the DZI URL or there is no possibility for someone to generate the state configuration (say from the Python SDK). The API as of now returns `{projectName}/{storageLocation}`. This too probably needs to be fixed.

**Comment by davidbirchwork** [comment]
@DavidAkroyd good idea, I will provide a reset button and API to processing state. 

@senakafdo the Asset service only knows about the asset file you upload. It cannot and will never know about a .dzi file, you will have to ask the image tile service for this.

**Comment by davidbirchwork** [comment]
@miguems @senakafdo  @DavidAkroyd latest commit features both an Enum translation and an API and website for resetting the processing state.
