### ISSUE TITLE
Restructure Repo

### ISSUE THREAD

**Issue by oserban** [ove/ove-services#6]
ATM this is mainly a a js structure, but we should adopt a polyglot structure:

- each service should have its own readme, docker and build script (linux by default + windows, if supported)
- a repo build script can be done, but it will become optional since all services have their own release cycle

**Comment by davidbirchwork** [comment]
We should be cross platform by default. 
The Repo is currently setup to run a single docker container to build and run all services under PM2. 
This seems sustainable for the present until we have a working Orchestrator service capable of spawning service instances. I do not want to pre-empt how this would work.

**Comment by senakafdo** [comment]
Adopting a polyglot structure is a good improvement, +1. However we need to note the following as well:
1. The lerna-based build system and the PM2 runtime environment that we have will be used by all JS projects such as OVE and OVE Apps. 
    - The services could in fact be developed in any language and this point does not apply.

2. The structure that we have in place right now is also convenient for building and running most other components provided that they do not need dedicated docker environments for their operations.
    - This point therefore doesn't apply to the Image Tile Service but would apply to anything that does not require their own containers. We cannot potentially be creating a container-per-service especially if we have many services which will be equally counter-productive since it will create a significant overhead in terms of running OVE services.

3. We will not always make design choices to suit the convenience of the developer. Our priorities are as follows (and @DavidAkroyd enforces this):
    1. Ops - It must be very convenient to run in production (not just @ the DSI but for anyone). Running != managing to get everything up - it also involves applying OS/software updates, error recovery etc.
    2. End Users - It must be super convenient for the end users and must not introduce additional ovehreads in terms of using OVE.
    3. Maintainers - It must be easy enough for any developer to extend/improve or maintain.
    4. Community Devs - It must be convenient for the external developers to fork and contribute to the project.
    5. Majority of Internal Devs - It must be convenient for DSI's dev team to work on the code
    6. Author of the work - they are at the bottom of the list and must ensure they don't impact anyone above them in order or priority.

So, while I'm very happy to go ahead with a polyglot structure, we need to ensure the above conditions are met by any change that we propose to the build or language we chose to develop. Same applies to any internal/external contributors.

So, there will of course be exceptions around service-specific docker containers etc. But, unless there is a really good reason as to why a service needs a dedicated docker container, that must be avoided. 

And, WRT .NET services, please feel free to contribute a [NUKE](https://nuke.build/) or other comparable build system - we can then get rid of the lerna dependency.

**Comment by senakafdo** [comment]
This issue was addressed following an offline discussion.
